### ISSUE TITLE
feat: add ability to deploy to different namespaces

### ISSUE THREAD

**Issue by saidsef** [saidsef/argocd-applicationsets-services#101]
As things stand, the chart will deploy all services to single namespace - declared globally.

I would be better to make the chart flexible and add the ability to to deploy each service to different namespace - if you so with.

We should keep the current behaviour as default, and add an option to override per service. 

for example:

```
repos:
  gitlab:
  - name: service-a
    path: 'deployment/preview'
    project: 13
    namespace: preview # <-- override
    repoUrl: 'https://gitlab.com/project/service-a.git'
```
